language: node_js
node_js:
  - '8'
script:
  - yarn lint
  - yarn test
branches:
  only:
  - master
cache:
    directories:
     - $HOME/.cache/yarn
     - ./packages/tests/base
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
