environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn --network-timeout 600000

test_script:
  - git --version
  - node --version
  - yarn --version
  - "node tests\\cli create ci"
  - yarn
  - "node tests\\cli test ci"

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules -> yarn.lock

build: off
