version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: ./.circleci/puppeteer.sh
      - run: yarn
      - run: yarn boot

      - save_cache:
          paths:
            - packages/base
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: ./tests/cli test ci
